import Image from "next/image";
import { ArrowDown, ArrowUpRight, Download, Github } from "lucide-react";
import ProjectGrid from "./project-grid";
import MobileNav from "./mobile-nav";

const skills = [
  { title: "Web & product", items: "Next.js / React / TypeScript / Tailwind CSS" },
  { title: "Mobile", items: "Kotlin / Jetpack Compose / Material 3 / Android APIs" },
  { title: "AI & data", items: "Python / XTTS / SQLite / Data visualization" },
  { title: "Foundations", items: "Algorithms / 8086 Assembly / Git & GitHub / LaTeX" },
];

export default function Home() {
  return <>
    <a className="skip-link" href="#main">Skip to content</a>
    <header className="site-header"><a className="brand" href="#top" aria-label="Tusar Imran — home">tusar<span>.</span></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#work">Work</a><a href="#about">About</a><a href="#education">Education</a><a href="#contact">Contact <ArrowUpRight size={14} aria-hidden="true" /></a></nav><a className="header-resume" href="/resume.pdf" download>Résumé <Download size={16} aria-hidden="true" /></a><MobileNav /></header>
    <main id="main">
      <section className="hero wrap" id="top" aria-labelledby="hero-title">
        <div className="hero-topline"><p className="eyebrow"><span className="small-cross" aria-hidden="true">+</span> SOFTWARE & AI PRODUCT BUILDER</p><span className="location">RAJSHAHI, BANGLADESH</span></div>
        <div className="hero-grid"><div className="hero-copy"><h1 id="hero-title">Useful ideas.<br />Thoughtful<br /><span>software.</span></h1><div className="hero-intro"><span className="intro-rule" aria-hidden="true"/><p>I’m <strong>MD. Tusar Imran.</strong> A RUET CSE undergraduate turning everyday problems into web, mobile and AI-enabled tools.</p></div><div className="hero-actions"><a className="button primary" href="#work">Explore my work <ArrowDown size={18} aria-hidden="true" /></a><a className="subtle-link" href="https://github.com/tusarimrananik" target="_blank" rel="noreferrer"><Github size={18} aria-hidden="true" /> GitHub <ArrowUpRight size={15} aria-hidden="true" /></a></div></div>
        <figure className="portrait"><div className="portrait-image"><Image src="/profile.jfif" alt="Portrait of MD. Tusar Imran" fill priority sizes="(max-width: 700px) 85vw, 35vw" /><span className="portrait-corner" aria-hidden="true"/><span className="portrait-index" aria-hidden="true">TI / 01</span></div><figcaption><span>THE PERSON BEHIND THE CODE</span><span>CSE · RUET</span></figcaption><div className="portrait-stamp" aria-hidden="true">BUILD.<br />LEARN.<br />REPEAT.<ArrowUpRight size={26}/></div></figure></div>
        <div className="hero-foot"><span>WEB · MOBILE · AUTOMATION · APPLIED AI</span><a href="#work">SCROLL TO EXPLORE <ArrowDown size={14} aria-hidden="true" /></a></div>
      </section>
      <section className="work-section wrap section" id="work" aria-labelledby="work-title"><div className="section-label"><span>01 / SELECTED WORK</span><span>IDEAS, MADE REAL.</span></div><div className="section-heading"><h2 id="work-title">Built with<br /><span>purpose.</span></h2><p>A collection of practical tools, experiments and platforms. Different problems. The same curiosity.</p></div><ProjectGrid/><a className="text-link repository-link" href="https://github.com/tusarimrananik?tab=repositories" target="_blank" rel="noreferrer">More in the repositories <ArrowUpRight size={18} aria-hidden="true" /></a></section>
      <section className="about-section section" id="about" aria-labelledby="about-title"><div className="wrap"><div className="section-label"><span>02 / A LITTLE ABOUT ME</span><span>CURIOUS BY DEFAULT.</span></div><div className="about-grid"><div><h2 id="about-title">Learn deeply.<br />Build <span>simply.</span></h2><span className="about-asterisk" aria-hidden="true">✳</span></div><div className="about-copy"><p className="large-copy">I like the space between a rough idea and something people can actually use.</p><p>My work connects computer-science fundamentals with practical product ideas—from browser extensions to Android utilities and AI-enabled tools. I enjoy finding the right technology for a problem, then making the experience clear.</p><p>At RUET, I study algorithms, data structures, numerical methods, microprocessors and microcontrollers alongside my software projects.</p><a className="text-link" href="/resume.pdf" download>Download my résumé <Download size={17} aria-hidden="true" /></a></div></div><div className="skills-list">{skills.map((skill, i) => <div className="skill" key={skill.title}><span className="skill-number">0{i + 1}</span><h3>{skill.title}</h3><p>{skill.items}</p></div>)}</div></div></section>
      <section className="education-section wrap section" id="education" aria-labelledby="education-title"><div className="section-label"><span>03 / EDUCATION</span><span>THE FOUNDATION.</span></div><div className="education-grid"><h2 id="education-title">Always<br /><span>learning.</span></h2><div className="education-list"><article><div className="education-date">2023 — PRESENT <span>UNDERGRADUATE</span></div><h3>B.Sc. in Computer Science & Engineering</h3><p>Rajshahi University of Engineering & Technology (RUET)</p><small>Rajshahi, Bangladesh · Session 2023–24 · Student ID 2303096</small></article><article><div className="education-date">2023</div><h3>Higher Secondary Certificate</h3><p>Hat Kanpara Jobedda College · Science</p><small>GPA 5.00 / 5.00</small></article><article><div className="education-date">2021</div><h3>Secondary School Certificate</h3><p>Hat Kanpara High School · Science</p><small>GPA 5.00 / 5.00</small></article></div></div></section>
      <section className="contact-section" id="contact" aria-labelledby="contact-title"><div className="wrap"><div className="section-label"><span>04 / GET IN TOUCH</span><span>GOOD THINGS START WITH A CONVERSATION.</span></div><a className="contact-heading" href="mailto:tusarimrananik@gmail.com"><h2 id="contact-title">Let’s talk.</h2><ArrowUpRight aria-hidden="true" /></a><div className="contact-bottom"><a className="email-link" href="mailto:tusarimrananik@gmail.com">tusarimrananik@gmail.com</a><p>A project idea, a question, or a hello.<br />I’d love to hear what you’re thinking.</p><a href="https://github.com/tusarimrananik" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={16} aria-hidden="true" /></a></div></div></section>
    </main><footer className="wrap"><span>© {new Date().getFullYear()} MD. Tusar Imran</span><span>THOUGHTFULLY BUILT. ALWAYS EVOLVING.</span><a href="#top">Back to top <ArrowUpRight size={14} aria-hidden="true" /></a></footer>
  </>;
}
